"""
mortgage.py
"""

PRINCIPAL = 500000.0
RATE = 0.05
PAYMENT = 2684.11
EXTRA_PAYMENT = 1000.0
EXTRA_PAYMENT_START_MONTH = 60
EXTRA_PAYMENT_END_MONTH = 108
TOTAL_PAYMENT = 0.0
TOTAL_PAID = 0.0
MONTHS_PAID = 0

while PRINCIPAL > 0:
    TOTAL_PAYMENT = PAYMENT

    if (
        (MONTHS_PAID >= EXTRA_PAYMENT_START_MONTH) and
        (MONTHS_PAID <= EXTRA_PAYMENT_END_MONTH)
    ):
        TOTAL_PAYMENT = PAYMENT + EXTRA_PAYMENT

    PRINCIPAL = PRINCIPAL * (1 + RATE / 12) - TOTAL_PAYMENT
    TOTAL_PAID = TOTAL_PAID + TOTAL_PAYMENT
    MONTHS_PAID = MONTHS_PAID + 1

print('Total paid', TOTAL_PAID)
print('Months paid', MONTHS_PAID)
