"""
mortgage.py
"""

PRINCIPAL = 500000.0
RATE = 0.05
PAYMENT = 2684.11
TOTAL_PAID = 0.0
MONTHS_PAID = 0
EXTRA_PAYMENT_MONTHS = 0

while PRINCIPAL > 0:
    if EXTRA_PAYMENT_MONTHS < 12:
        PAYMENT = 3684.11
        EXTRA_PAYMENT_MONTHS = EXTRA_PAYMENT_MONTHS + 1
    else:
        PAYMENT = 2684.11

    PRINCIPAL = PRINCIPAL * (1 + RATE / 12) - PAYMENT
    TOTAL_PAID = TOTAL_PAID + PAYMENT
    MONTHS_PAID = MONTHS_PAID + 1


print('Total paid', TOTAL_PAID)
print('Months paid', MONTHS_PAID)
