"""
mortgage.py
"""

PRINCIPAL = 500000.0
RATE = 0.05
PAYMENT = 2684.11
TOTAL_PAID = 0.0

while PRINCIPAL > 0:
    PRINCIPAL = PRINCIPAL * (1 + RATE / 12) - PAYMENT
    TOTAL_PAID = TOTAL_PAID + PAYMENT

print('Total paid', TOTAL_PAID)
